{
	"sites":[
	{
		"name":"Timberclub",
		"domain":"timberclubaustralia.com.au",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":false,
		"nsfw":false
	},{
		"name":"THN Partners",
		"domain":"thnpartners.com.au",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":false,
		"nsfw":false
	},{
		"name":"Sydney Garden Lodge",
		"domain":"sydgardenlodge.com.au",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":false,
		"nsfw":false
	},{
		"name":"Jessie Coffee School",
		"domain":"jessiecoffee.com.au",
		"wp":true,
		"ec":true,
		"ct":true,
		"tt":true,
		"nsfw":false
	},{
		"name":"South Pacific Resort Hotel",
		"domain":"southpacresort.com.au",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":true,
		"nsfw":false
	},{
		"name":"Asian Butterfly Massage",
		"domain":"asianbutterflymassage.com.au",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":false,
		"nsfw":true
	},{
		"name":"National Car Rental",
		"domain":"nationalcarrentals.com.au",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":false,
		"nsfw":false
	},{
		"name":"test",
		"domain":"",
		"wp":true,
		"ec":false,
		"ct":true,
		"tt":false,
		"nsfw":false
	}
	]
}
